# Simulation options
TIME_STEPS = 500

GRID_X = 150
GRID_Y = 150

#Visualization options
class VisualizationOptions:
    FPS = 5
    CELLS_PER_INCH = 5
    PIXELS_PER_CELL = 5
    PIXELS_PER_ENTITY = 6 # May be larger than pixels per cell
    PIXELS_PER_INCH = CELLS_PER_INCH * PIXELS_PER_CELL
    FILE_NAME = "video"
    BG_COLOR = "darkblue"

# Initialization settings
FISH_START_RADIUS = 8
FISH_START_COUNT = 2
FISH_START_CHANCE = 0.3
FISH_REINFORCEMENT_CHANCE = 0.05

FOOD_START_COUNT = 10
FOOD_PER_STEP = 3

SHARK_START_COUNT = 12

# Fish settings
FISH_VISION = 2
FISH_RANDOMNESS = 0.3

# Fish influence factors
SHARK_FACTOR = 5
FOOD_ATTRACTION = 3
OBSTACLE_FACTOR = 1.2
COHESION_STRENGTH = 0.6

# Shark settings
SHARK_SPEED = 0.8
SHARK_VISION = 4

# Obstacle settings 

DENSITY_OBSTACLE = 0.3
THRESHOLD_OBSTACLE = 0.3

# Time settings
DAYTIME_DURATION = 60
NIGHTTIME_DURATION = 40
DAYTIME_VISION_BONUS = 1
