TIME_STEPS = 30

GRID_X = 32
GRID_Y = 32

# Only mode 6 is supported
MODE_4, MODE_6, MODE_8 = 0,1,2
GRID_MODE = MODE_6

FISH_START_RADIUS = 2
FISH_START_COUNT = 3
FISH_START_CHANCE = 0.7

FISH_VISION = 2

SHARK_START_COUNT = 3
SHARK_FACTOR = 5
SHARK_VISION = 3